// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BabySteps",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "BabySteps",
            targets: ["AppModule"],
            bundleIdentifier: "igormax.dev.BabySteps",
            teamIdentifier: "M77366DRWS",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "The microphone is required to analyze and classify your baby's crying patterns, helping you better understand their needs.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/InfantCryClassifier.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)